project_name: alertmanager-webhook-space
version: 2

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/alertmanager-webhook-space/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ns3777k/alertmanager-webhook-space:{{ .Tag }}"
      - "ns3777k/alertmanager-webhook-space:latest"
